### ISSUE TITLE
Error ERR_CERT_REVOKED

### ISSUE THREAD

**Issue by aidan-waite** [thenativeweb/wolkenkit-template-chat#6]
Followed the steps in the readme. Server and client appeared to start correctly. Chat doesn't work and the below errors are in the console. Please advise. I'm not a web dev so please be gentle. PS. I tried creating a local SSL cert and adding it to keys. Was never able to get this working properly. Thanks.

I also tried changing ports and configuring the local cert with the path and package.json and etc. etc. and no combination of certs and paths worked. The closest I got was getting a CORS error instead of an SSL error.

> request.js:159 GET https://local.wolkenkit.io:3000/v1/ping?_=1576870360277 net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> index.js:63 Error: Failed to get configuration.
>     at ConfigurationWatcher.wentOffline (ConfigurationWatcher.js:102)
>     at eval (ConfigurationWatcher.js:89)
>     at tryCatch (es6-promise.js:408)
>     at invokeCallback (es6-promise.js:423)
>     at publish (es6-promise.js:397)
>     at publishRejection (es6-promise.js:338)
>     at MutationObserver.flush (es6-promise.js:127)
> run @ index.js:63
> async function (async)
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/configuration.json net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> eval @ ConfigurationWatcher.js:129
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getConfigurationFromServer @ ConfigurationWatcher.js:128
> wentOnline @ ConfigurationWatcher.js:74
> ConfigurationWatcher @ ConfigurationWatcher.js:53
> eval @ getApp.js:46
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> Wss.js:46 WebSocket connection to 'wss://local.wolkenkit.io:3000/' failed: Error in connection establishment: net::ERR_CERT_REVOKED
> Wss @ Wss.js:46
> eval @ getApp.js:54
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> request.js:159 GET https://local.wolkenkit.io:3000/v1/configuration.json net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> eval @ ConfigurationWatcher.js:129
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getConfigurationFromServer @ ConfigurationWatcher.js:128
> wentOnline @ ConfigurationWatcher.js:74
> onceWrapper @ events.js:238
> emit @ events.js:151
> online @ NetworkConnection.js:54
> eval @ NetworkConnection.js:86
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/ping?_=1576870362294 net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/configuration.json net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> eval @ ConfigurationWatcher.js:129
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getConfigurationFromServer @ ConfigurationWatcher.js:128
> wentOnline @ ConfigurationWatcher.js:74
> onceWrapper @ events.js:238
> emit @ events.js:151
> online @ NetworkConnection.js:54
> eval @ NetworkConnection.js:86
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/ping?_=1576870364304 net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/configuration.json net::ERR_CERT_REVOKED
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> eval @ ConfigurationWatcher.js:129
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getConfigurationFromServer @ ConfigurationWatcher.js:128
> wentOnline @ ConfigurationWatcher.js:74
> onceWrapper @ events.js:238
> emit @ events.js:151
> online @ NetworkConnection.js:54
> eval @ NetworkConnection.js:86
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> eval @ NetworkConnection.js:91
> setTimeout (async)
> eval @ NetworkConnection.js:90
> onResEnd @ request.js:41
> emit @ events.js:151
> endReadableNT @ _stream_readable.js:1010
> afterTickTwo @ index.js:28
> Item.run @ browser.js:153
> drainQueue @ browser.js:123
> setTimeout (async)
> runTimeout @ browser.js:41
> process.nextTick @ browser.js:143
> nextTick @ index.js:27
> resume @ _stream_readable.js:783
> Readable.resume @ _stream_readable.js:775
> Readable.on @ _stream_readable.js:745
> eval @ request.js:57
> setResHeaders @ request.js:104
> xhr.onreadystatechange @ request.js:138
> XMLHttpRequest.send (async)
> eval @ request.js:159
> onceWrapper @ events.js:238
> emit @ events.js:146
> finishMaybe @ _stream_writable.js:630
> endWritable @ _stream_writable.js:638
> Writable.end @ _stream_writable.js:594
> request @ request.js:81
> test @ NetworkConnection.js:76
> NetworkConnection @ NetworkConnection.js:43
> eval @ getApp.js:45
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> getApp @ getApp.js:42
> eval @ wolkenkitClient.js:41
> setTimeout (async)
> eval @ wolkenkitClient.js:33
> initializePromise @ es6-promise.js:457
> Promise @ es6-promise.js:873
> connect @ wolkenkitClient.js:32
> run @ index.js:27
> eval @ index.js:67
> ./src/index.js @ main.js:4331
> __webpack_require__ @ main.js:727
> fn @ main.js:101
> eval @ client:2
> 1 @ main.js:4342
> __webpack_require__ @ main.js:727
> (anonymous) @ main.js:794
> (anonymous) @ main.js:797
> request.js:159 GET https://local.wolkenkit.io:3000/v1/ping?_=1576870366313 net::ERR_CERT_REVOKED

**Comment by goloroden** [comment]
> I'm not a web dev so please be gentle.

No problem 😊

> PS. I tried creating a local SSL cert and adding it to keys.

How did you do that? Can you share the contents of your `package.json` file, and the path of where you put the certificate? And, the file names of the certificate and the private key?

**Comment by goloroden** [comment]
Closed due to inactivity.
